BOOKS = 'books'
CULTURAL_CENTERS = 'cultural_centers'
EVENTS = 'events'
LIBRARIES = 'libraries'
COUNT_VECTORIZER = 'count_vectorizer'
WORD2VEC = 'word2vec'
GENRES = 'GENRES'

LDA = 'lda'
BOOKS_LDA = BOOKS + '_' + LDA
EVENTS_LDA = EVENTS + '_' + LDA
CULTURAL_CENTERS_LDA = CULTURAL_CENTERS + '_' + LDA
LIBRARIES_LDA = LIBRARIES + '_' + LDA

BOOKS_COUNT_VECTORIZER = BOOKS + '_' + COUNT_VECTORIZER
EVENTS_COUNT_VECTORIZER = EVENTS + '_' + COUNT_VECTORIZER
CULTURAL_CENTERS_COUNT_VECTORIZER = CULTURAL_CENTERS + '_' + COUNT_VECTORIZER
LIBRARIES_COUNT_VECTORIZER = LIBRARIES + '_' + COUNT_VECTORIZER

SIMILAR_BOOKS = 'SIMILAR' + BOOKS
SIMILAR_EVENTS = 'SIMILAR' + EVENTS
SIMILAR_CULTURAL_CENTERS = "SIMILAR" + CULTURAL_CENTERS
SIMILAR_LIBRARIES = "SIMILAR" + LIBRARIES

FILTER_MATRIX_USERS_BOOKS = 'filter_matrix_users_books'
FILTER_MATRIX_USERS_EVENTS = 'filter_matrix_users_events'
FILTER_MATRIX_USERS_CULTURAL_CENTERS = 'filter_matrix_users_cultural_centers'
PREPROCESSING_BOOKS = 'preprocessing_books'
PREPROCESSING_CONTENT_BOOKS = 'preprocessing_content_books'
PREPROCESSING_EVENTS = 'preprocessing_events'
PREPROCESSING_CONTENT_EVENTS = 'preprocessing_content_events'
PREPROCESSING_CULTURAL_CENTERS = 'preprocessing_cultural_centers'
PREPROCESSING_CONTENT_CULTURAL_CENTERS = 'preprocessing_content_cultural_centers'

PREPROCESSING_LIBRARIES = 'preprocessing_libraries'
PREPROCESSING_CONTENT_LIBRARIES = 'preprocessing_content_libraries'

FILTERING_MODEL_BOOKS = 'filtering_model_' + BOOKS
FILTERING_MODEL_EVENTS = 'filtering_model_' + EVENTS
FILTERING_MODEL_CULTURAL_CENTERS = 'filtering_model_' + CULTURAL_CENTERS
