# Generated by Django 3.1.2 on 2020-10-15 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_book', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('serie', models.CharField(max_length=255)),
                ('rating', models.FloatField()),
                ('language', models.CharField(max_length=255)),
                ('image', models.URLField()),
                ('content', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='CultureCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_center', models.IntegerField()),
                ('adress', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('web_site', models.URLField()),
                ('underground', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('title', models.CharField(max_length=255)),
                ('image', models.URLField()),
                ('content', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_event', models.IntegerField()),
                ('town', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('age_rate', models.IntegerField()),
                ('web_site', models.URLField()),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('image', models.URLField()),
                ('content', models.CharField(max_length=1000)),
                ('id_culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.culturecenter')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_genre', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_library', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('adress', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('phone_number', models.CharField(max_length=255)),
                ('social_net', models.URLField()),
                ('work_time', models.CharField(max_length=1000)),
                ('image', models.URLField()),
                ('content', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('age', models.IntegerField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='LastEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.event')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.user')),
            ],
        ),
        migrations.CreateModel(
            name='LastBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.book')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.user')),
            ],
        ),
        migrations.CreateModel(
            name='GenreBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.book')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.genre')),
            ],
        ),
        migrations.CreateModel(
            name='BooksInLibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.book')),
                ('id_library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.library')),
            ],
        ),
    ]
