# Generated by Django 3.1.2 on 2020-10-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20201015_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='culturecenter',
            name='web_site',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id_user',
        ),
        migrations.AddField(
            model_name='culturecenter',
            name='social_site',
            field=models.URLField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='social_net',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
