# Generated by Django 3.1.2 on 2020-10-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20201015_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='culturecenter',
            old_name='social_site',
            new_name='social_net',
        ),
        migrations.RemoveField(
            model_name='book',
            name='id_book',
        ),
        migrations.RemoveField(
            model_name='culturecenter',
            name='id_center',
        ),
        migrations.RemoveField(
            model_name='event',
            name='id_event',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='id_genre',
        ),
        migrations.RemoveField(
            model_name='library',
            name='id_library',
        ),
        migrations.AddField(
            model_name='culturecenter',
            name='web_site',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='culturecenter',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='library',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='library',
            name='work_time',
            field=models.TextField(),
        ),
    ]
