# Generated by Django 3.1.2 on 2020-10-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_book_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='library',
            name='web_site',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='library',
            name='social_net',
            field=models.TextField(),
        ),
    ]
