# Generated by Django 3.1.2 on 2020-10-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20201016_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culturecenter',
            name='social_net',
            field=models.TextField(),
        ),
    ]
