# Generated by Django 3.1.2 on 2020-10-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20201016_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culturecenter',
            name='number',
            field=models.CharField(max_length=255),
        ),
    ]
