# Generated by Django 3.1.2 on 2020-10-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20201016_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='age_rate',
            field=models.CharField(max_length=255),
        ),
    ]
