# Generated by Django 3.1.2 on 2020-10-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20201017_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastbooks',
            name='score',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='lastcenter',
            name='score',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='lastevents',
            name='score',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
