# Generated by Django 3.1.2 on 2020-10-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20201029_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastbook',
            name='status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lastcenter',
            name='status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lastevent',
            name='status',
            field=models.IntegerField(),
        ),
    ]
