# Generated by Django 3.1.2 on 2020-10-31 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20201031_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lastcenter',
            name='id_center',
        ),
        migrations.RemoveField(
            model_name='lastcenter',
            name='id_user',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='age_category',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='town',
            new_name='date_end',
        ),
        migrations.RemoveField(
            model_name='event',
            name='id_culture',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.RemoveField(
            model_name='event',
            name='social_net',
        ),
        migrations.RemoveField(
            model_name='event',
            name='web_site',
        ),
        migrations.AddField(
            model_name='event',
            name='date_start',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='follow_event',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='goal_auditory',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='holiday',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='name_center',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='name_district',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='name_holiday',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='time_end',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='time_start',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='type_center',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='type_event',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CultureCenter',
        ),
        migrations.DeleteModel(
            name='LastCenter',
        ),
    ]
